image: docker:latest

services:
  - docker:dind

build:
  stage: build
  script:
    - export CONTAINER_BUILD_IMAGE=$DOCKER_REGISTRY/$DOCKER_NAMESPACE/rancher-deploy:latest
    - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD $DOCKER_REGISTRY
    - docker build --pull -t $CONTAINER_BUILD_IMAGE .
    - docker push $CONTAINER_BUILD_IMAGE
    - docker rmi $CONTAINER_BUILD_IMAGE